name: Build ESP32-S3 Selector

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup ESP-IDF
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.2

      - name: Build selector
        shell: bash
        run: |
          cd selector
          idf.py set-target esp32s3
          idf.py build -v

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: |
            selector/build/**/*.bin
